version: '3'

services:
  frontend:
    build: ./react-app
    container_name: reactapp_c
    ports:
      - '5173:5173'
  backend:
    build: ./node-server
    container_name: backend_c
    ports:
      - '5000:5000'