version: '3'

services:
  postgresDB:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dncc
    ports:
      - '5432:5432'
  backend:
    build: ./node-server
    container_name: backend_c
    # command: sh -c "npx prisma migrate deploy --preview-feature && npm start"
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgresDB:5432/dncc?schema=public
    links:
      - postgresDB
    depends_on:
      - postgresDB
    ports:
      - '5000:5000'
  frontend:
    build: ./react-app
    container_name: reactapp_c
    depends_on:
      - backend
    ports:
      - '5173:5173'
